### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ggris** [ggris/rubx#1]
class Camera
- Projection matrix

class Texture -> Chantal
 -Crée une texture en chargeant un fichier
 -Accès au GLuint correspondant

class displayableCube -> Guillaume

class RubixCube -> Totor
 -état du rcube
 -fourni la position des petits cubes à CHAQUE instant
 -transition
 -mélange
 -victoire

Shaders ...
Gestion des évennements -> Alexandre
Interface
Ombres par shadow-map

class Lamp

**Comment by AlexandreCHamelin** [comment]
Est-ce que vous avez réussi à faire fonctionner le projet sur windows? J'arrive à compiler, mais j'ai une erreur "access violation" parce que le pointeur de la fonction "glGenVertexArrays" est null...

**Comment by ggris** [comment]
J'en suis au même point sauf que moi c'est glBindVertexArray qui a un
pointeur nul

2015-04-15 21:37 GMT+02:00 AlexandreCHamelin notifications@github.com:

> Est-ce que vous avez réussi à faire fonctionner le projet sur windows?
> J'arrive à compiler, mais j'ai une erreur "access violation" parce que le
> pointeur de la fonction "glGenVertexArrays" est null...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ggris/rubx/issues/1#issuecomment-93542673.

## 

Guillaume Gris
_Promotion X2011_

**Comment by ggris** [comment]
Bon, je suis arrivé à faire marcher le truc sous windows. J'ai commité ma
version windows-valide.

Il faut avoir installé glew correctement.
Le dossier "shader" est copié dans le dossier bin à la compilation mais VS
met l'exécutable dans bin/Debug donc il faut copier le dossier de shaders
dans bin/Debug manuellment pour le moment.
Comme le dossier de shaders n'est pas à la racine de l'exécutable VS, le
bouton dans VS pour lancer l'exécutable en mode débug marchera mais le
programme lui-même ne donnera rien car il manquera les shaders.

2015-04-15 22:18 GMT+02:00 Guillaume Gris guillaume.gris@polytechnique.org
:

> J'en suis au même point sauf que moi c'est glBindVertexArray qui a un
> pointeur nul
> 
> 2015-04-15 21:37 GMT+02:00 AlexandreCHamelin notifications@github.com:
> 
> > Est-ce que vous avez réussi à faire fonctionner le projet sur windows?
> > J'arrive à compiler, mais j'ai une erreur "access violation" parce que le
> > pointeur de la fonction "glGenVertexArrays" est null...
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ggris/rubx/issues/1#issuecomment-93542673.
> 
> ## 
> 
> Guillaume Gris
> _Promotion X2011_

## 

Guillaume Gris
_Promotion X2011_

**Comment by AlexandreCHamelin** [comment]
Bon, j'ai réussi à le faire fonctionner aussi.
