### ISSUE TITLE
gestion des évènements

### ISSUE THREAD

**Issue by ggris** [ggris/rubx#5]
Implémenter une classe de gestion des évènements.

**Comment by AlexandreCHamelin** [comment]
Essentiellement rendu à la sélection d'objets par raypicking.
Je pense prendre cette technique:
http://antongerdelan.net/opengl/raycasting.html

Il faudra aussi détecter qu'on ne click pas sur un objet pour faire tourner le rubix cube en entier

**Comment by AlexandreCHamelin** [comment]
Pour les évenements une fois qu'on aura détecté un mouse press sur une face d'un petit cube, on veux gérer les déplacements comment? À mon avis on devrait faire soit un click and drag ou un click qui crée une rotation. 

Ce serait bien d'avoir une fonction click sur les objets qui vont être déplacés pour que ce soit facile de passer les événements.

**Comment by ggris** [comment]
Je suis d'accord pour l'idée du click and drag.
Il faut voir comment on peut intégrer ça dans la classe rubix. Je regarderai plus en détail quand Victor aura un truc plus ou moins fonctionnel.

**Comment by AlexandreCHamelin** [comment]
Les sc mesh ils ont que le vao. Comment je calcule les intersections de ray avec ça? Des idées?

**Comment by AlexandreCHamelin** [comment]
J'ai ajouté une "bouding box" sur les cubes pour le calcul des intersections et j'ai trouvé un algorithme pour les trouver. Je pense que je n'ai pas mis les bonnes matrices dans les fonctions getProjectionMat et GetViewMat dans la camera et que c'est pour ça que ça ne fonctionne pas. Est-ce que quelqu'un peut vérifier ces deux fonctions, je ne sais pas quelles matrices retourner.

**Comment by AlexandreCHamelin** [comment]
Finalement après pas mal d'effort pour debug la sélection par raycast j'ai abandonné et j'ai utilisé une solution qui redessine les objets voulus une fois avec des couleurs uniques qui sont ensuite utilisées pour les identifier et ça fonctionne :D

**Comment by ggris** [comment]
Nice, ça avance bien, ça fait plaisir ! C'est intéressant comme solution mais du coup tu calcules l'image deux fois ?

**Comment by tal-chan** [comment]
Je vais faire un peu de ménage dans le dossier scene pour réorganiser le scène 3D et intégrer les lampes. Tu peux me dire sur quels fichiers tu travailles principalement pour qu'on évite les conflits de merge ?

**Comment by AlexandreCHamelin** [comment]
Je travaille pas en ce moment

**Comment by AlexandreCHamelin** [comment]
Ouais on recalcule l'image deux fois, mais juste quand on click. C'est pas idéal mais ça lagera pas on n'a pas une grosse scène

**Comment by AlexandreCHamelin** [comment]
Pour le UI, demain ou peut-être ce soir, je vais faire les menus finaux avec une sélection sur les options parce qu'il faut pouvoir entrer une difficulté et un nom d'utilisateur pour le score.

Demain soir le ui devrais donc être fini ainsi que la gestion des pointages. 

Je vais surement faire un cleanup de la classe UI également et faire la classe game pour redémarrer le timer à chaque fois qu'on fait une nouvelle partie et enregistrer le score lorsqu'on quitte la partie.

La classe game devrais aussi réinitialiser le rubix cube à sa version réussi et jouer un nombre X de coups aléatoires en fonction de la difficulté sélectionnée dans le menu principale. Tout ça quand on démarre une nouvelle partie.

Ce serais bien d'avoir un cube centré demain et de pouvoir commencer à le manipuler.

**Comment by ggris** [comment]
Pour ce qui est du cube centré, je m'en suis occupé tout à l'heure.

**Comment by AlexandreCHamelin** [comment]
demain matin tout le monde viens?

**Comment by ggris** [comment]
Je pense que oui

**Comment by AlexandreCHamelin** [comment]
good :)

**Comment by AlexandreCHamelin** [comment]
Si jamais on a le temps pour ajouter des trucs "fancy" pour s'amuser, à partir de ma classe 2dpanel on devrait être capable de faire des sprite 2d assez facilement en suivant le meme principe que ma classe sctext mais en appliquant un facteur de temps aux coordonnées de texture

**Comment by AlexandreCHamelin** [comment]
J'ai un écran noir dans la scène de jeu c'est normal?

**Comment by ggris** [comment]
Essaies de re-copier les shaders

**Comment by AlexandreCHamelin** [comment]
j'ai une erreur dans le shader ggx

**Comment by AlexandreCHamelin** [comment]
undefined variable base_position

**Comment by ggris** [comment]
En effet, base_position n'existe plus dans la nouvelle version du vert_shader. Tu as probablement un truc quelque part qui l'utilise encore et qui ne devrait pas. Sur ma version, rien ne l'utilise.

**Comment by AlexandreCHamelin** [comment]
C'est bon ça c'est réglé tout seul lol. Pour moi visual studio n,avait pas rechargé l'un des fichiers

**Comment by AlexandreCHamelin** [comment]
hmm si jamais vous changez la fonction display sur le mesh essayé de l'ajuster sur la fonction displayWithPickingColour aussi. Je l'ai fix, mais ce serais sympa les prochaines fois lol

**Comment by AlexandreCHamelin** [comment]
J'y ai pensé et il faut vraiment que ce sois le grand cube qui tourne et non la caméra pour pouvoir voir le dessous du cube. On pourrait avoir les deux, disons le cube avec clique droit enfoncé et la caméra avec le bouton du milieu de la souris enfoncé, mais il faut pouvoir tourner le grand cube

**Comment by AlexandreCHamelin** [comment]
Y'a un cube qui n'est pas au bon endroit à l'initialisation
