### ISSUE TITLE
Write fragment shaders

### ISSUE THREAD

**Issue by ggris** [ggris/rubx#7]
advanced fragment shaders
- mirror
- normal map

**Comment by tal-chan** [comment]
Ajouté la gestion des lampes multiples à ggx, reste toujours à ajouter les coordonnées cameras correctes mais même en dehors de ça le comportement du shader n'est pas normal. Ajouter des lampes n'augmente pas la luminosité, typiquement, et certaines faces des cubes restent toujours dans l'ombre quelles que soient l'angle des lampes. L'erreur ne vient pas de la transmission de données, a priori le shader reçoit bien les valeurs des lampes correctement. En estspérant que corriger la caméra permet d'obtenir de bon résultats, mais je suis tentée de tout réécrire. Je vais peut-être aussi écrire un shader plus simple (lambert+blinn phong) histoire qu'on ait un truc qui marche même si ggx fait n'importe quoi.

**Comment by tal-chan** [comment]
Corrigé la valeur de fragPosition pour tenir compte de la matrice de transformation. GGX donne des valeurs négatives, créé un fix temporaire en remplaçant les valeurs négatives par 0. ça marche mais je ne sais pas s'il est normal d'obtenir des valeurs négatives au départ...
